// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.17.3
// source: ad_business_overpass.proto

package ad_business_overpass

import (
	ad_base_overpass "github.com/zbwang163/ad_base_overpass"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AddCoinsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Coins int32                         `protobuf:"varint,1,opt,name=coins,proto3" json:"coins,omitempty"`
	Base  *ad_base_overpass.BaseRequest `protobuf:"bytes,15,opt,name=base,proto3" json:"base,omitempty"`
}

func (x *AddCoinsRequest) Reset() {
	*x = AddCoinsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ad_business_overpass_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddCoinsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddCoinsRequest) ProtoMessage() {}

func (x *AddCoinsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ad_business_overpass_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddCoinsRequest.ProtoReflect.Descriptor instead.
func (*AddCoinsRequest) Descriptor() ([]byte, []int) {
	return file_ad_business_overpass_proto_rawDescGZIP(), []int{0}
}

func (x *AddCoinsRequest) GetCoins() int32 {
	if x != nil {
		return x.Coins
	}
	return 0
}

func (x *AddCoinsRequest) GetBase() *ad_base_overpass.BaseRequest {
	if x != nil {
		return x.Base
	}
	return nil
}

type AddCoinsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data *AddCoinsResponse_AddCoinsData `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Base *ad_base_overpass.BaseResponse `protobuf:"bytes,15,opt,name=base,proto3" json:"base,omitempty"`
}

func (x *AddCoinsResponse) Reset() {
	*x = AddCoinsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ad_business_overpass_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddCoinsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddCoinsResponse) ProtoMessage() {}

func (x *AddCoinsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ad_business_overpass_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddCoinsResponse.ProtoReflect.Descriptor instead.
func (*AddCoinsResponse) Descriptor() ([]byte, []int) {
	return file_ad_business_overpass_proto_rawDescGZIP(), []int{1}
}

func (x *AddCoinsResponse) GetData() *AddCoinsResponse_AddCoinsData {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *AddCoinsResponse) GetBase() *ad_base_overpass.BaseResponse {
	if x != nil {
		return x.Base
	}
	return nil
}

type AddCoinsResponse_AddCoinsData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Coins int32 `protobuf:"varint,1,opt,name=coins,proto3" json:"coins,omitempty"`
}

func (x *AddCoinsResponse_AddCoinsData) Reset() {
	*x = AddCoinsResponse_AddCoinsData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ad_business_overpass_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddCoinsResponse_AddCoinsData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddCoinsResponse_AddCoinsData) ProtoMessage() {}

func (x *AddCoinsResponse_AddCoinsData) ProtoReflect() protoreflect.Message {
	mi := &file_ad_business_overpass_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddCoinsResponse_AddCoinsData.ProtoReflect.Descriptor instead.
func (*AddCoinsResponse_AddCoinsData) Descriptor() ([]byte, []int) {
	return file_ad_business_overpass_proto_rawDescGZIP(), []int{1, 0}
}

func (x *AddCoinsResponse_AddCoinsData) GetCoins() int32 {
	if x != nil {
		return x.Coins
	}
	return 0
}

var File_ad_business_overpass_proto protoreflect.FileDescriptor

var file_ad_business_overpass_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x61, 0x64, 0x5f, 0x62, 0x75, 0x73, 0x69, 0x6e, 0x65, 0x73, 0x73, 0x5f, 0x6f, 0x76,
	0x65, 0x72, 0x70, 0x61, 0x73, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x16, 0x61, 0x64,
	0x5f, 0x62, 0x61, 0x73, 0x65, 0x5f, 0x6f, 0x76, 0x65, 0x72, 0x70, 0x61, 0x73, 0x73, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0x49, 0x0a, 0x0f, 0x41, 0x64, 0x64, 0x43, 0x6f, 0x69, 0x6e, 0x73,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x69, 0x6e, 0x73,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x63, 0x6f, 0x69, 0x6e, 0x73, 0x12, 0x20, 0x0a,
	0x04, 0x62, 0x61, 0x73, 0x65, 0x18, 0x0f, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x42, 0x61,
	0x73, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x04, 0x62, 0x61, 0x73, 0x65, 0x22,
	0x8f, 0x01, 0x0a, 0x10, 0x41, 0x64, 0x64, 0x43, 0x6f, 0x69, 0x6e, 0x73, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x32, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x41, 0x64, 0x64, 0x43, 0x6f, 0x69, 0x6e, 0x73, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x41, 0x64, 0x64, 0x43, 0x6f, 0x69, 0x6e, 0x73, 0x44, 0x61,
	0x74, 0x61, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x12, 0x21, 0x0a, 0x04, 0x62, 0x61, 0x73, 0x65,
	0x18, 0x0f, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x42, 0x61, 0x73, 0x65, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52, 0x04, 0x62, 0x61, 0x73, 0x65, 0x1a, 0x24, 0x0a, 0x0c, 0x41,
	0x64, 0x64, 0x43, 0x6f, 0x69, 0x6e, 0x73, 0x44, 0x61, 0x74, 0x61, 0x12, 0x14, 0x0a, 0x05, 0x63,
	0x6f, 0x69, 0x6e, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x63, 0x6f, 0x69, 0x6e,
	0x73, 0x32, 0x44, 0x0a, 0x0f, 0x42, 0x75, 0x73, 0x69, 0x6e, 0x65, 0x73, 0x73, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x12, 0x31, 0x0a, 0x08, 0x41, 0x64, 0x64, 0x43, 0x6f, 0x69, 0x6e, 0x73,
	0x12, 0x10, 0x2e, 0x41, 0x64, 0x64, 0x43, 0x6f, 0x69, 0x6e, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x11, 0x2e, 0x41, 0x64, 0x64, 0x43, 0x6f, 0x69, 0x6e, 0x73, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x2b, 0x5a, 0x29, 0x67, 0x69, 0x74, 0x68, 0x75,
	0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x7a, 0x62, 0x77, 0x61, 0x6e, 0x67, 0x31, 0x36, 0x33, 0x2f,
	0x61, 0x64, 0x5f, 0x62, 0x75, 0x73, 0x69, 0x6e, 0x65, 0x73, 0x73, 0x5f, 0x6f, 0x76, 0x65, 0x72,
	0x70, 0x61, 0x73, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_ad_business_overpass_proto_rawDescOnce sync.Once
	file_ad_business_overpass_proto_rawDescData = file_ad_business_overpass_proto_rawDesc
)

func file_ad_business_overpass_proto_rawDescGZIP() []byte {
	file_ad_business_overpass_proto_rawDescOnce.Do(func() {
		file_ad_business_overpass_proto_rawDescData = protoimpl.X.CompressGZIP(file_ad_business_overpass_proto_rawDescData)
	})
	return file_ad_business_overpass_proto_rawDescData
}

var file_ad_business_overpass_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_ad_business_overpass_proto_goTypes = []interface{}{
	(*AddCoinsRequest)(nil),               // 0: AddCoinsRequest
	(*AddCoinsResponse)(nil),              // 1: AddCoinsResponse
	(*AddCoinsResponse_AddCoinsData)(nil), // 2: AddCoinsResponse.AddCoinsData
	(*ad_base_overpass.BaseRequest)(nil),  // 3: BaseRequest
	(*ad_base_overpass.BaseResponse)(nil), // 4: BaseResponse
}
var file_ad_business_overpass_proto_depIdxs = []int32{
	3, // 0: AddCoinsRequest.base:type_name -> BaseRequest
	2, // 1: AddCoinsResponse.data:type_name -> AddCoinsResponse.AddCoinsData
	4, // 2: AddCoinsResponse.base:type_name -> BaseResponse
	0, // 3: BusinessService.AddCoins:input_type -> AddCoinsRequest
	1, // 4: BusinessService.AddCoins:output_type -> AddCoinsResponse
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_ad_business_overpass_proto_init() }
func file_ad_business_overpass_proto_init() {
	if File_ad_business_overpass_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_ad_business_overpass_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddCoinsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ad_business_overpass_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddCoinsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ad_business_overpass_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddCoinsResponse_AddCoinsData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_ad_business_overpass_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ad_business_overpass_proto_goTypes,
		DependencyIndexes: file_ad_business_overpass_proto_depIdxs,
		MessageInfos:      file_ad_business_overpass_proto_msgTypes,
	}.Build()
	File_ad_business_overpass_proto = out.File
	file_ad_business_overpass_proto_rawDesc = nil
	file_ad_business_overpass_proto_goTypes = nil
	file_ad_business_overpass_proto_depIdxs = nil
}
